---
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - /srv/changedetection/data:/datastore
    env_file:
      - /srv/env/changedetection.env
    restart: unless-stopped
    networks:
      - caddy
      - changedetection-backend
    labels:
      - homepage.group=Services.Right
      - homepage.name=Change Detection
      - homepage.icon=sh-changedetection.svg
      - homepage.href=https://cdio.domain.tld
      - homepage.description=Web Site Change Monitoring
      - homepage.widget.type=changedetectionio
      - homepage.widget.url=https://cdio.domain.tld
      - homepage.widget.key=${CDIO_KEY}
    depends_on:
      sockpuppetbrowser:
        condition: service_started

  sockpuppetbrowser:
    hostname: sockpuppetbrowser
    container_name: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    env_file:
      - /srv/env/sockpuppet.env
    networks:
      - changedetection-backend
    labels:
      - homepage.group=Headless
      - homepage.name=Sock Puppet Browser
      - homepage.icon=sh-chromium.svg
      - homepage.description=Chrome Engine for Change Detection
      - homepage.showStats=true

networks:
  caddy:
    external: true
  changedetection-backend:
    driver: bridge