services:
  lldap:
    image: lldap/lldap:stable
    name: lldap-server
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
    volumes:
      - "/srv/lldap/data:/data"
      - "/srv/lldap/certs:/certs"
    networks:
      - lldap-backend
      - lldaps
      - caddy
    env_file:
      - /src/env/lldap.env
      

    db:
      image: postgres:14
      container_name: lldap-db
      env_file:
        - .env
      networks:
        - lldap-backend
      volumes:
        - lldap-db:/var/lib/postgresql/data
      restart: unless-stopped

volumes:
  lldap-db:
    driver: local
    external: true
  lldap_data:
    driver: local

networks:
  caddy:
    external: true
  lldap-backend:
    external: true
  lldaps:
    external: true