services:
  lldap:
    image: lldap/lldap:stable
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "/srv/lldap/data:/data"
      - "/srv/lldap/certs:/certs"
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Boise
      - LLDAP_JWT_SECRET=REPLACE_WITH_RANDOM
      - LLDAP_KEY_SEED=REPLACE_WITH_RANDOM
      - LLDAP_LDAP_BASE_DN=dc=durish,dc=xyz
      - LLDAP_LDAP_USER_PASS=adminPas$word
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/certs/certfile.crt
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/certs/keyfile.key
      - LLDAP_DATABASE_URL=postgres://lldapsvc:<password>d@lldap-db/lldap
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - LLDAP_SMTP_OPTIONS__SERVER=smtp.example.com
      - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp providor's documentation for this setting
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
      - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
      - LLDAP_SMTP_OPTIONS__FROM=no-reply <no-reply@example.com> # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
      - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.

    db:
      image: postgres:14
      container_name: lldap-db
      env_file:
        - .env
      networks:
        - lldap-backend
      volumes:
        - lldap-db:/var/lib/postgresql/data
      restart: unless-stopped

volumes:
  lldap-db:
    driver: local
    external: true
  lldap_data:
    driver: local