---
services:
  caddy:
    build: .
    container_name: caddy
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - /srv/caddy:/etc/caddy
    env_file:
      - /srv/env/caddy.env
    networks:
      - caddy
      - gluetun-caddy
    ports:
      - 2019:2019
      - 80:80
      - 443:443
    labels:
      - homepage.group=Services.Right
      - homepage.name=Caddy
      - homepage.icon=sh-caddy.svg
      - homepage.description=Reverse Proxy Service
      - homepage.widget.type=caddy
      - homepage.widget.url=http://${CADDY_HOST}.domain.tld:2019
      - caddy=(tinyauth_forwarder)
      - caddy.forward_auth=tinyauth:3000
      - caddy.forward_auth.uri=/api/auth/caddy

volumes:
  caddy_config:
    driver: local
  caddy_data:
    driver: local

networks:
  caddy:
    external: true
  gluetun-caddy:
    external: true