---
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    env_file:
      - /srv/env/changedetection.env
    restart: unless-stopped
    networks:
      - caddy
      - changedetection-backend
    depends_on:
      sockpuppetbrowser:
        condition: service_started


     # Sockpuppetbrowser is basically chrome wrapped in an API for allowing fast fetching of web-pages.
     # RECOMMENDED FOR FETCHING PAGES WITH CHROME, be sure to enable the "PLAYWRIGHT_DRIVER_URL" env variable in the main changedetection container
  sockpuppetbrowser:
    hostname: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    env_file:
      - /srv/env/sockpuppet.env
    networks:
      - changedetection-backend
#        cap_add:
#            - SYS_ADMIN
# SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci


volumes:
  changedetection-data:

networks:
  caddy:
    external: true
  changedetection-backend:
    driver: bridge