---
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    env_file:
      - /srv/env/changedetection.env
    restart: unless-stopped
    networks:
      - caddy
      - changedetection-backend
    labels:
      - homepage.group=Services
      - homepage.name=Change Detection
      - homepage.icon=sh-changedetection.svg
      - homepage.href=https://cdio.durish.xyz
      - homepage.description=Web Site Change Monitoring
      - homepage.widget.type=changedetectionio
      - homepage.widget.href=changedetection
      - homepage.widget.key=${CDIO_KEY}
    depends_on:
      sockpuppetbrowser:
        condition: service_started

  sockpuppetbrowser:
    hostname: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    env_file:
      - /srv/env/sockpuppet.env
    networks:
      - changedetection-backend

volumes:
  changedetection-data:

networks:
  caddy:
    external: true
  changedetection-backend:
    driver: bridge