services:
  otterwiki:
    image: redimp/otterwiki:2
    container_name: otterwiki
    restart: unless-stopped
    env_file:
      - /srv/env/otterwiki.env
    networks:
      - caddy
    volumes:
      - /srv/otterwiki/data:/app-data

networks:
  caddy:
    external: true