services:
  otterwiki:
    image: redimp/otterwiki:2
    container_name: otterwiki
    restart: unless-stopped
    env_file:
      - /srv/env/otterwiki.env
    networks:
      - caddy
    volumes:
      - /srv/otterwiki/data:/app-data
    labels:
      - homepage.group=Services.Right
      - homepage.name=OtterWiki
      - homepage.icon=sh-an-otter-wiki.png
      - homepage.href=https://otterwiki.domain.tld

networks:
  caddy:
    external: true