---
services:
  server:
    image: gitea/gitea:1.23.5
    container_name: gitea-server
    env_file:
      .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - caddy
      - gitea-backend
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2221:22"
    depends_on:
      - db
    restart: unless-stopped
    labels:
      - homepage.group=Development
      - homepage.name=Gitea
      - homepage.icon=si-gitea-#609926
      - homepage.href=https://git.durish.xyz
      - homepage.description=Remote Repository

  db:
    image: postgres:14
    container_name: gitea-db
    env_file:
      - .env
    networks:
      - gitea-backend
    volumes:
      - gitea-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  gitea-data:
    driver: local
  gitea-db:
    driver: local

networks:
  caddy:
    external: true
  gitea-backend:
    external: true