---
services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    env_file:
      - /srv/env/common.env
    volumes:
      - /srv/tvheadend/data:/config
      - /srv/tvheadend/recordings:/recordings
    networks:
      - tvheadend
    ports:
      - 9981:9981
      - 9982:9982
    restart: unless-stopped
    labels:
      - homepage.group=arrSuite.Core
      - homepage.name=TVHeadend
      - homepage.icon=sh-tbheadend.webp
      - homepage.href=https://tv.domain.tld
      - homepage.description=TV Streaming Solution

networks:
  tvheadend: {}