---
services:
  caddy:
    build: .
    container_name: caddy
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - /srv/caddy/Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - /srv/env/caddy.env
    networks:
      - caddy
    ports:
      - 2019:2019
      - 80:80
      - 443:443
    labels:
      - homepage.group=Core
      - homepage.name=caddy
      - homepage.icon=si-caddy.svg
      - homepage.description=Reverse Proxy Service

volumes:
  caddy_config:
    driver: local
  caddy_data:
    driver: local

networks:
  caddy:
    external: true