---
services:
  caddy:
    build: .
    container_name: caddy
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./Caddyfile.prd:/etc/caddy/Caddyfile
    env_file:
      - .env
    networks:
      - caddy
    ports:
      - 2019:2019
      - 80:80
      - 443:443

volumes:
  caddy_config:
    driver: local
  caddy_data:
    driver: local

networks:
  caddy:
    external: true