services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    env_file:
      - /srv/env/common.env
      - /srv/env/jellyfin.env
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /srv/arrsuite/Media:/media:ro
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - homepage.group=arrSuite.core
      - homepage.name=Jellyfin
      - homepage.icon=sh-jellyfin.svg
      - homepage.href=https://watch.domain.tld
      - homepage.description=Media Player
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://watch.domain.tld
      - homepage.widget.key=${JELLYFIN_API_TOKEN}
      - homepage.widget.enableUser=true
      - homepage.widget.showEpisodeNumber=true