services:
  gluetun-proxy:
    image: qmcgaw/gluetun
    container_name: gluetun-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - gluetun-proxy
      - gluetun-caddy
    ports:
      - 8000:8000 # Control Server
      - 8889:8889 # Gluetun
      - 8888:8888/tcp # TCP Proxy
      - 8388:8388/tcp # Shadowsocks TCP
    volumes:
      - /srv/gluetun/proxy:/gluetun
    env_file:
      # Gluetun Wiki Reference: https://github.com/qdm12/gluetun-wiki 
      - /srv/env/gluetun-proxy.env
    restart: unless-stopped
    labels:
      - homepage.group=Services.Center
      - homepage.name=Gluetun Proxy
      - homepage.icon=sh-mullvad-vpn.svg
      - homepage.description=Network Proxy Services
      - homepage.widget.type=gluetun
      - homepage.widget.url=http://gtp.domain.tld:8000

  firefox-proxy:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox-proxy
    security_opt:
      - seccomp:unconfined #optional
    env_file:
      - /srv/env/common.env
    volumes:
      - /srv/firefox/proxy/config:/config
    network_mode: service:gluetun-proxy
    labels:
      - homepage.group=Services.Right
      - homepage.name=Firefox
      - homepage.icon=sh-firefox.svg
      - homepage.description=Proxied Browsing
      - homepage.href=https://safe.domain.tld
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      gluetun-proxy:
        condition: service_started

networks:
  gluetun-proxy:
    external: true
  gluetun-caddy:
    external: true