services:
  gluetun-proxy:
    image: qmcgaw/gluetun
    container_name: gluetun-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - gluetun-proxy
    ports:
      - 8889:8889/tcp # Gluetun
      - 3000:3000/tcp # Firefox
      - 3000:3000/udp # Firefox
      - 1025:8888/tcp # TCP Proxy
      - 1025:8888/udp # UDP Proxy
      - 1026:8388/tcp # Shadowsocks TCP
      - 1026:8388/udp # Shadowsocks UDP
    volumes:
      - /srv/gluetun/proxy:/gluetun
    env_file:
      # Gluetun Wiki Reference: https://github.com/qdm12/gluetun-wiki 
      - /srv/env/gluetun-proxy.env
    restart: unless-stopped
    labels:
      - homepage.section=Core
      - homepage.name=Gluetun Proxy
      - homepage.description=Network Proxy Services
      - homepage.icon=sh-mullvad.svg
      - homepage.widget.type=gluetun
      - homepage.widget.url=http://gtp.domain.tld

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Boise
    volumes:
      - /srv/firefox/config:/config
    network_mode: service:gluetun-proxy
    labels:
      - homepage.section=Services
      - homepage.name=Firefox
      - homepage.description=Proxied Browsing
      - homepage.icon=sh-firefox.svg
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      gluetun-proxy:
        condition: service_started

networks:
  gluetun-proxy:
    external: true